// Expanded sample data
export const peopleData = [
    { 
      id: 1,
      type: 'ghost',
      position: [8.5241, 76.9366],
      name: "Spirit of Captain James Moore",
      deathDate: "1892-03-15",
      deathReason: "Lost at sea during a great storm",
      age: 45,
      details: "Appears on stormy nights, warning sailors of dangerous waters",
      lastSeen: "Last full moon at midnight",
      hauntingPower: "Strong",
      manifestationType: "Full apparition"
    },
    { 
      id: 2,
      type: 'ghost',
      position: [8.5244, 76.9370],
      name: "Lady Victoria Bennett",
      deathDate: "1923-11-30",
      deathReason: "Mysterious disappearance from the old mansion",
      age: 28,
      details: "Plays the piano in the abandoned east wing",
      lastSeen: "Every midnight",
      hauntingPower: "Moderate",
      manifestationType: "Musical manifestation"
    },
    {
      id: 3,
      type: 'ghost',
      position: [8.5238, 76.9375],
      name: "Child Spirit Tommy",
      deathDate: "1955-06-12",
      deathReason: "Tragic playground accident",
      age: 8,
      details: "Giggles heard near the old school playground",
      lastSeen: "During school hours",
      hauntingPower: "Gentle",
      manifestationType: "Auditory and partial visual"
    },
    {
      id: 4,
      type: 'living',
      position: [8.5242, 76.9368],
      name: "Dr. Sarah Chen",
      age: 35,
      occupation: "Paranormal Researcher",
      health: "Excellent",
      details: "Leading expert in spectral energy detection",
      dailyRoutine: "Conducts research from 9 PM to 3 AM",
      equipment: "Advanced EMF detectors, thermal cameras",
      specialty: "Ghost communication"
    },
    {
      id: 5,
      type: 'living',
      position: [8.5246, 76.9372],
      name: "Marcus Thompson",
      age: 42,
      occupation: "Historical Architect",
      health: "Good",
      details: "Renovates haunted buildings while preserving their history",
      dailyRoutine: "Site visits during daylight hours",
      expertise: "Victorian architecture",
      currentProject: "Old mansion restoration"
    },
    {
      id: 6,
      type: 'living',
      position: [8.5240, 76.9373],
      name: "Luna Martinez",
      age: 27,
      occupation: "Medium",
      health: "Sensitive to spiritual energy",
      details: "Can communicate with spirits",
      dailyRoutine: "Conducts séances at dusk",
      abilities: "Clairvoyance, spirit channeling",
      specialty: "Helping spirits find peace"
    },
    {
      id: 7,
      type: 'ghost',
      position: [8.4837, 76.8963], // Significantly spaced from original cluster
      name: "William 'Red' Morgan",
      deathDate: "1876-08-22",
      deathReason: "Killed in a saloon brawl",
      age: 32,
      details: "Ghost appears with a phantom bullet wound, challenging visitors to duels",
      lastSeen: "During full moons",
      hauntingPower: "Moderate",
      manifestationType: "Full apparition with gunslinger outfit"
    },
    {
      id: 8,
      type: 'living',
      position: [8.5843, 76.9771], // Different direction spacing
      name: "Dr. Emily Richardson",
      age: 45,
      occupation: "Parapsychologist",
      health: "Good",
      details: "Specializes in analyzing ghostly energy patterns",
      dailyRoutine: "Studies haunting patterns from midnight to dawn",
      equipment: "Custom-built EMF detectors",
      specialty: "Spectral energy mapping"
    },
    {
      id: 9,
      type: 'ghost',
      position: [8.4939, 76.9567],
      name: "Sister Mary Catherine",
      deathDate: "1901-12-24",
      deathReason: "Pneumonia while caring for orphans",
      age: 52,
      details: "Still watches over children in the old orphanage",
      lastSeen: "Christmas Eve annually",
      hauntingPower: "Gentle",
      manifestationType: "Ethereal nun figure with healing presence"
    },
    {
      id: 10,
      type: 'living',
      position: [8.5645, 76.8866],
      name: "Jack Zhang",
      age: 29,
      occupation: "Tech Specialist",
      health: "Excellent",
      details: "Develops new ghost detection equipment",
      dailyRoutine: "Tests equipment during peak haunting hours",
      equipment: "Prototype spectral sensors",
      specialty: "Digital spirit photography"
    },
    {
      id: 11,
      type: 'ghost',
      position: [8.5140, 77.0165],
      name: "Elizabeth 'Betty' Crawford",
      deathDate: "1955-09-15",
      deathReason: "Tragic dance hall fire",
      age: 23,
      details: "Dances eternally in the rebuilt ballroom",
      lastSeen: "During evening events",
      hauntingPower: "Strong",
      manifestationType: "Dancing apparition in vintage dress"
    },
    {
      id: 12,
      type: 'living',
      position: [8.4538, 76.9163],
      name: "Maria Gonzalez",
      age: 51,
      occupation: "Ghost Tour Guide",
      health: "Good",
      details: "Leads haunted history tours through the old district",
      dailyRoutine: "Evening tours from 7 PM to midnight",
      expertise: "Local haunted history",
      specialty: "Victorian era hauntings"
    },
    {
      id: 13,
      type: 'ghost',
      position: [8.5943, 76.9265],
      name: "Captain Samuel Hawthorne",
      deathDate: "1845-11-03",
      deathReason: "Lost in a shipwreck",
      age: 58,
      details: "Patrols the harbor warning of incoming storms",
      lastSeen: "Before major storms",
      hauntingPower: "Strong",
      manifestationType: "Misty figure with glowing lantern"
    },
    {
      id: 14,
      type: 'living',
      position: [8.4737, 76.9967],
      name: "Dr. Robert Chen",
      age: 62,
      occupation: "Paranormal Historian",
      health: "Fair",
      details: "Documents historical hauntings and their connections",
      dailyRoutine: "Research and interviews during daylight",
      expertise: "Ancient burial grounds",
      specialty: "Archaeological hauntings"
    },
    {
      id: 15,
      type: 'ghost',
      position: [8.5441, 76.8763],
      name: "Little Emma Thompson",
      deathDate: "1918-02-14",
      deathReason: "Spanish Flu epidemic",
      age: 7,
      details: "Plays in the garden with spectral toys",
      lastSeen: "During spring afternoons",
      hauntingPower: "Gentle",
      manifestationType: "Partial apparition with laughter"
    },
    {
      id: 16,
      type: 'living',
      position: [8.5843, 76.9363],
      name: "Detective James Morrison",
      age: 39,
      occupation: "Paranormal Investigator",
      health: "Excellent",
      details: "Investigates supernatural cold cases",
      dailyRoutine: "Night investigations and day research",
      equipment: "Full spectrum cameras",
      specialty: "Cold case hauntings"
    },
    {
      id: 17,
      type: 'ghost',
      position: [8.4637, 76.9565],
      name: "Professor Harold Wright",
      deathDate: "1932-09-28",
      deathReason: "Laboratory accident",
      age: 65,
      details: "Still conducts experiments in the old physics lab",
      lastSeen: "During electrical storms",
      hauntingPower: "Strong",
      manifestationType: "Electronic interference and partial apparition"
    },
    {
      id: 18,
      type: 'living',
      position: [8.5741, 76.8965],
      name: "Sophia Patel",
      age: 33,
      occupation: "Spirit Photographer",
      health: "Good",
      details: "Captures supernatural phenomena on film",
      dailyRoutine: "Photography sessions at golden hour",
      equipment: "Modified infrared cameras",
      specialty: "Capturing orbs and ectoplasm"
    },
    {
      id: 19,
      type: 'ghost',
      position: [8.4839, 77.0063],
      name: "Judge Ezra Stone",
      deathDate: "1888-07-04",
      deathReason: "Murdered by a convicted criminal",
      age: 61,
      details: "Still holds court in the abandoned courthouse",
      lastSeen: "Midnight court sessions",
      hauntingPower: "Powerful",
      manifestationType: "Full apparition in judicial robes"
    },
    {
      id: 20,
      type: 'living',
      position: [8.5539, 76.9163],
      name: "Lisa Wong",
      age: 28,
      occupation: "Psychic Medium",
      health: "Sensitive to spiritual energies",
      details: "Communicates with recently departed spirits",
      dailyRoutine: "Conducts readings and cleansings",
      abilities: "Clear audience and clairvoyance",
      specialty: "Family reconciliations"
    },
    {
      id: 21,
      type: 'ghost',
      position: [8.5144, 76.9462],
      name: "Madame Isabella Rossi",
      deathDate: "1905-08-19",
      deathReason: "Poisoned during an opera performance",
      age: 38,
      details: "Sings arias in the abandoned theater",
      lastSeen: "During rehearsals and performances",
      hauntingPower: "Strong",
      manifestationType: "Vocal manifestation with partial apparition"
    },
    {
      id: 22,
      type: 'living',
      position: [8.5346, 76.9268],
      name: "Dr. Alexander Foster",
      age: 56,
      occupation: "Ectoplasm Specialist",
      health: "Good",
      details: "Studies physical manifestations of spirits",
      dailyRoutine: "Laboratory analysis from dusk to midnight",
      equipment: "Ectoplasm collection devices",
      specialty: "Physical ghost interactions"
    },
    {
      id: 23,
      type: 'ghost',
      position: [8.5047, 76.9163],
      name: "Conductor Charles Winston",
      deathDate: "1889-12-01",
      deathReason: "Train collision in heavy fog",
      age: 49,
      details: "Still signals trains with his phantom lantern",
      lastSeen: "Foggy nights near the old tracks",
      hauntingPower: "Moderate",
      manifestationType: "Glowing figure with lantern"
    },
    {
      id: 24,
      type: 'living',
      position: [8.5442, 76.9561],
      name: "Nina Blackwood",
      age: 31,
      occupation: "Supernatural Archaeologist",
      health: "Excellent",
      details: "Excavates haunted historical sites",
      dailyRoutine: "Daytime excavation, evening analysis",
      equipment: "Ground-penetrating radar",
      specialty: "Ancient burial sites"
    },
    {
      id: 25,
      type: 'ghost',
      position: [8.5139, 76.9264],
      name: "Nurse Helen Graham",
      deathDate: "1918-11-11",
      deathReason: "Contracted Spanish Flu from patients",
      age: 29,
      details: "Still checks on patients in the old hospital ward",
      lastSeen: "During medical emergencies",
      hauntingPower: "Gentle",
      manifestationType: "Healing presence and soft footsteps"
    },
    {
      id: 26,
      type: 'living',
      position: [8.5243, 76.9467],
      name: "Professor Takashi Yamamoto",
      age: 47,
      occupation: "Quantum Ghost Theorist",
      health: "Good",
      details: "Researches quantum mechanics of hauntings",
      dailyRoutine: "Conducts experiments at quantum labs",
      equipment: "Quantum field detectors",
      specialty: "Interdimensional ghost theory"
    },
    {
      id: 27,
      type: 'ghost',
      position: [8.5341, 76.9365],
      name: "Librarian Margaret Whitmore",
      deathDate: "1952-04-15",
      deathReason: "Crushed by falling bookshelf",
      age: 56,
      details: "Organizes books after hours",
      lastSeen: "Midnight in the reference section",
      hauntingPower: "Moderate",
      manifestationType: "Book-moving poltergeist"
    },
    {
      id: 28,
      type: 'living',
      position: [8.5147, 76.9269],
      name: "Father Michael O'Connor",
      age: 65,
      occupation: "Paranormal Priest",
      health: "Fair",
      details: "Performs spiritual cleansings",
      dailyRoutine: "Prayer sessions and blessings",
      equipment: "Holy water and blessed items",
      specialty: "Demonic hauntings"
    },
    {
      id: 29,
      type: 'ghost',
      position: [8.5442, 76.9168],
      name: "Chef Antoine Dupont",
      deathDate: "1934-06-22",
      deathReason: "Kitchen fire in his restaurant",
      age: 42,
      details: "Still cooks in his old kitchen at midnight",
      lastSeen: "During dinner service hours",
      hauntingPower: "Moderate",
      manifestationType: "Phantom cooking smells and utensil movement"
    },
    {
      id: 30,
      type: 'living',
      position: [8.5245, 76.9364],
      name: "Dr. Amara Johnson",
      age: 38,
      occupation: "Ghost Psychology Researcher",
      health: "Excellent",
      details: "Studies ghost behavior patterns",
      dailyRoutine: "Evening observation sessions",
      equipment: "Behavioral monitoring devices",
      specialty: "Spirit trauma analysis"
    },
    {
      id: 31,
      type: 'ghost',
      position: [8.5143, 76.9267],
      name: "Blacksmith Thomas Cooper",
      deathDate: "1867-09-03",
      deathReason: "Forge accident",
      age: 39,
      details: "Phantom hammering heard from old forge",
      lastSeen: "During harvest moon",
      hauntingPower: "Strong",
      manifestationType: "Auditory and thermal manifestation"
    },
    {
      id: 32,
      type: 'living',
      position: [8.5246, 76.9368],
      name: "Raven Nightshade",
      age: 25,
      occupation: "Occult Researcher",
      health: "Good",
      details: "Studies ancient ghost summoning rituals",
      dailyRoutine: "Research at witching hour",
      equipment: "Crystal balls and pendulums",
      specialty: "Historical séances"
    },
    {
      id: 33,
      type: 'ghost',
      position: [8.5144, 76.9366],
      name: "Seamstress Mary Sullivan",
      deathDate: "1912-04-15",
      deathReason: "Titanic sinking",
      age: 24,
      details: "Sewing sounds from her old shop",
      lastSeen: "Anniversary of Titanic sinking",
      hauntingPower: "Gentle",
      manifestationType: "Phantom sewing machine sounds"
    },
    {
      id: 34,
      type: 'living',
      position: [8.5242, 76.9365],
      name: "Felix Blackwood",
      age: 41,
      occupation: "Ghost Photography Expert",
      health: "Good",
      details: "Develops new spirit photography techniques",
      dailyRoutine: "Midnight photo sessions",
      equipment: "Modified digital cameras",
      specialty: "Capturing ghost orbs"
    },
    {
      id: 35,
      type: 'ghost',
      position: [8.5241, 76.9363],
      name: "Lighthouse Keeper David Ross",
      deathDate: "1883-10-31",
      deathReason: "Fall from lighthouse tower",
      age: 51,
      details: "Still maintains the lighthouse light",
      lastSeen: "Stormy nights",
      hauntingPower: "Strong",
      manifestationType: "Light phenomena and full apparition"
    },
    {
      id: 36,
      type: 'living',
      position: [8.5243, 76.9367],
      name: "Dr. Isabella Santos",
      age: 36,
      occupation: "Paranormal Acoustics Expert",
      health: "Excellent",
      details: "Records and analyzes EVP phenomena",
      dailyRoutine: "Night recording sessions",
      equipment: "High-sensitivity microphones",
      specialty: "Ghost voice analysis"
    },
    {
      id: 37,
      type: 'ghost',
      position: [8.5242, 76.9364],
      name: "Schoolmaster George Pembroke",
      deathDate: "1901-02-28",
      deathReason: "Influenza epidemic",
      age: 59,
      details: "Still teaches in abandoned classroom",
      lastSeen: "During school hours",
      hauntingPower: "Moderate",
      manifestationType: "Chalk writing and voice manifestation"
    },
    {
      id: 38,
      type: 'living',
      position: [8.5244, 76.9366],
      name: "Mei Lin",
      age: 29,
      occupation: "Spiritual Energy Healer",
      health: "Sensitive to energies",
      details: "Helps spirits and living find peace",
      dailyRoutine: "Evening healing sessions",
      equipment: "Crystal healing tools",
      specialty: "Energy cleansing"
    },
    {
      id: 39,
      type: 'ghost',
      position: [8.5245, 76.9365],
      name: "Mayor Richard Sterling",
      deathDate: "1922-07-04",
      deathReason: "Assassination at town parade",
      age: 54,
      details: "Appears during town celebrations",
      lastSeen: "Independence Day ceremonies",
      hauntingPower: "Strong",
      manifestationType: "Full apparition in formal attire"
    },
    {
      id: 40,
      type: 'living',
      position: [8.5246, 76.9364],
      name: "Dr. Benjamin Walker",
      age: 43,
      occupation: "Paranormal Statistics Analyst",
      health: "Good",
      details: "Analyzes patterns in ghost appearances",
      dailyRoutine: "Data collection at haunted sites",
      equipment: "Statistical modeling software",
      specialty: "Haunting frequency analysis"
    }
  ];